### ISSUE TITLE
Exercises List

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#1]
## Value proposition
As a user
I want to browse a list of exercises,
so that I can discover new exercises to include in my workouts.

## Description
<img src="https://github.com/user-attachments/assets/47014a3a-f00c-4d71-b01d-a7704a17b26b" alt="Wireframe #1" width="200"/>

## Acceptance criteria
- [x] The homepage displays a list of exercises.
- [x] The exercises list is headlined with its purpose.
- [x] Each exercise listing includes: Exercise name, Exercise image, Targeted muscle groups
- [x] The list supports vertical scrolling to accommodate multiple entries.

## Tasks
- [x]  Create feature branch feature/exercises-list
- [x]  Inspect and adapt the example data in the [assets folder](https://github.com/neuefische/hh-web-24-5/blob/main/capstone/workout-planner/assets/exercises.json)
- [x]  Add an imageUrl for each exercise, for example from [unsplash.com](https://github.com/neuefische/hh-web-24-5/blob/main/capstone/workout-planner/unsplash.com)
------
- [x]  Create the component ExercisesList to render a list
- [x]  ExercisesList props: exercises
- [x]  Create the component ExercisePreview
- [x]  ExercisePreview props: name, muscleGroups, imageUrl
