### ISSUE TITLE
Outsource Workout Form

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#16]
## Value proposition
As a user
I want to open the create form on another page with a button click
In order to keep my workouts list organized

## Description
<img src="https://github.com/user-attachments/assets/35ec1d90-2497-4d58-8a51-7bdf0ce89f84" alt="Wireframe #8" width="150"/>
<img src="https://github.com/user-attachments/assets/b157aaef-e6c4-415f-bf06-2c8f92888be2" alt="Wireframe #8" width="150"/>

## Acceptance criteria
- [x] The workouts list page includes an easily accessible button to create a new workout.
- [x] Clicking the button opens a new page with the existing form.
- [x] A back button allows the user to back out of the create process if selected by mistake or if they change their mind.
- [x] Upon submitting the form, the user is immediately redirected to the workouts list page, and the new workout is saved and reflected.

## Tasks
- [x] Create feature branch feature/outsource-form
- [x] In the WorkoutsList component, add a create workout button
- [x] By clicking the button open the page pages/workouts/create
- [x] The page renders the WorkoutForm component including all corresponding props
- [x] Add a back button, which leads the user to pages/workouts
- [x] Upon submitting the form, the user should be redirected back to pages/workouts
- [x] Remove the existing form from the WorkoutsList
