### ISSUE TITLE
Implement design in app

### ISSUE THREAD

**Issue by VanessaDiBella** [jukrams/workout-planner#17]
## Value proposition
As a user
I want to use a well designed app
In order to have a better user experience.
## Description
![Home](https://github.com/user-attachments/assets/c506be3b-d2ac-475e-9351-d38f91cfa6f5)
![Design for Excercise List (1)](https://github.com/user-attachments/assets/c429ca6c-0f39-438e-bbac-b7d00587f3a3)
![Design for Excercise Details](https://github.com/user-attachments/assets/070d57bf-f048-4704-8f46-f97b681615f4)
![Design for Workout List (2)](https://github.com/user-attachments/assets/75df38c5-57f2-4350-a7f6-4f15f1207323)
![Design for Workout List (3)](https://github.com/user-attachments/assets/a0f7fdf8-6554-4262-9667-75cc34fb7fc8)
![Design for Workout Form](https://github.com/user-attachments/assets/7bb81170-b588-4cd1-9b9d-6908d7d9c453)
![Design for UpdateForm](https://github.com/user-attachments/assets/fef74fbb-483d-4721-85a3-b4f693804ce2)
![Design for Exercise Filter open](https://github.com/user-attachments/assets/024ac598-aaab-4a9e-b218-545c17ea2dd2)
![Design for Exercise Filter closed](https://github.com/user-attachments/assets/bbb5d974-6c9d-4e91-9a15-7486181f452b)

## Acceptance criteria
- [ ] The app has a CI with defined colors, forms and fonts
- [ ] Images should be showing the exercise
## Tasks
- [ ] Create a new branch for the styling
- [ ] Create global styles for colors, fonts, margin
- [ ] Create a new assets folder in lib for the icons and backgrounds
- [ ] import icons as SVG
- [ ] import background images as png or jpg
- [ ] Create styled-components for submit, clear, save, add, favorite, and go back buttons
- [ ] Create hover styled-components for each button
- [ ] Create styled-components for muscle tags
- [ ] Create styled-components for name tags

**Comment by Roland-Hufnagel** [comment]
Good userstory. Some suggestions are:
- `Recognizable design with repeated use of styled-components` -> 'styled-components' is an implementation detail which you can define as a task but not in the AC. 
- A few more tasks would be nice. E.g. Create global styles. Define global variables for colors and fonts, install and use styled-components,...

**Comment by Roland-Hufnagel** [comment]
LGTM
