### ISSUE TITLE
Workout Details

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#18]
## Value proposition
As a user
I want to be able to like to show and hide details about my workouts
In order to have a good overview of my workouts

## Description
<img src="https://github.com/user-attachments/assets/ab97019b-9a74-4959-9210-74dfda397a1e" alt="Wireframe #9" width="150"/>
<img src="https://github.com/user-attachments/assets/f3f281df-ec36-4a51-a074-a95dc996d290" alt="Wireframe #9" width="150"/>

## Acceptance criteria
- [x] The workouts list page includes an easily accessible details button for each workout.
- [x] Clicking the details option expands the card and shows more information including exercises, sets and reps.
- [x] Clicking the option again reduces the card. Only the workout's name and muscle groups are visible.

## Tasks
- [x] Create branch feature/workout-details
- [x]  Workout cards include an easily accessible button labeled with "Show more" for each workout.
- [x] Create a useState(false) for "isDetailsMode"
- [x] Clickling the button sets isDetailsMode "true"
- [x] Implement isDetailsMode in the  workout component
- [x] If details mode is true, change the text to "Show less"
- [x] Use a ternary operator to show and hide exercises, sets and reps according to isDetailsMode
- [x] Clickling the button "Show less" sets isDetailsMode "false"

**Comment by Roland-Hufnagel** [comment]
Hi. This is a good idea 💡 of showing vs hiding the details instead of having a dynamic detailspage. 
Nevertheless here are some suggestions:
- `The workouts list includes an easily accessible button labeled with "Show more" for each workout.` => not the list but each workout card should include that button. 
- a better name for the useState is `isDetailsMode`. That indicates that it is a boolean value.
- You don't have to pass that useState to the appropriate workout component. Instead it should be implemented in the workout component.

**Comment by Roland-Hufnagel** [comment]
Looks good 😀
