### ISSUE TITLE
Add Home page

### ISSUE THREAD

**Issue by VanessaDiBella** [jukrams/workout-planner#19]
## Value proposition
As a user
I want to have a start page
To get welcomed and to navigate clearly through my app
## Description
![Home](https://github.com/user-attachments/assets/e1e9e7de-954f-492b-bd09-03ea62b51090)
## Acceptance criteria
- [x] Needs to have the name of the app as a highlight
- [x] Short description of what the app is about
- [x] A Link that navigates to the exercise List
## Tasks
- [x] Create a new branch called feature/home
- [x] Create a new file in pages called home.js
- [x] Create a styled Component for the Link component in the components folder
- [x] Create a styled Component for h1  in the components folder
- [x] Create a styled Component for h2  in the components folder
- [x] Create a new Component in home.js that returns the styled-components of h1, h2 and the Link that navigates to the exercise page
- [x] Style the page as shown in the description while using global styling

**Comment by Roland-Hufnagel** [comment]
LGTM
