### ISSUE TITLE
Exercise Details

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#2]
## Value proposition
As a user
I want to access detailed information about each exercise,
so that I can effectively utilize them in my workout routines.

## Description
<img src="https://github.com/user-attachments/assets/70b27f9c-6630-4137-b5c2-2300b8eb65a3" alt="Wireframe #2" width="400"/>

## Acceptance criteria
- [x] Each exercise in the exercises list has a link to a details page.
- [x] Each details page contains: Exercise name, Exercise image, Targeted muscle groups, Step-by-step instructions
- [x] The detailed view includes a “back” link, allowing users to easily navigate back to the list of exercises.
## Tasks
- [x] Create feature branch feature/exercise-details
- [x] -----
- [x] Create the component ExerciseDetails
- [x] ExerciseDetails props: name, imageUrl, muscleGroups, instructions
- [x] Create the page pages/exercises/[id].js that renders ExerciseDetails
- [x] Read the query parameter id from next/router
- [x] Use the id to find the exercise to display
- [x] Add a "back" link to go back to pages/index.js
