### ISSUE TITLE
Workout Favourites

### ISSUE THREAD

**Issue by VanessaDiBella** [jukrams/workout-planner#24]
## Value proposition
As a user
I want to highlight my favourite workouts
In order to find them quicker
## Description
![Design for Workout List (2)](https://github.com/user-attachments/assets/100c571e-a188-476a-b81b-46bb28827c7c)
## Acceptance criteria 
- [x] An icon button is added on every workout card
- [x] That icon should be clickable and change color, when it's clicked as favourite
- [x] An icon button is added on top of the workout-list page
- [x] Clicking the top icon button filters every as favourite marked workout and displays it on the same page
- [x] Clicking the favourite button on a non-favorite workout saves it as a favorite
- [x] Clicking the favourite button on a favorite workout removes it from favourites
## Tasks
- [x] Create a new branch called feature/favourite-workout
- [x] Go to the component folder and create a new styled favourite-button component
- [x]  Create an additional local storage state workoutInfo to save further information for workouts
- [x] Make the workoutInfo state globally available for all workout pages
- [x] Store the state in the workoutInfo
- [x] Reference workouts by id in the additional state
- [x] Create the component FavouriteButton
- [x] FavoriteButton props: isFavourite, onToggleFavorite
- [x] Render the FavouriteButton component in the Workout component
- [x]  Use data from the workoutInfo state to filter for all favourite workouts
- [x] Pass the list of all favourite workouts via prop to the WorkoutsPage component

**Comment by Roland-Hufnagel** [comment]
Good story. I want to mention two things:
`Store the favourite Icon in the workoutInfo` I think you don't want to store the icon but the state 😀.
And I recommend to choose another icon but the 'star'. The star is typically associated with a rating instead of a bookmark.
