### ISSUE TITLE
Switch pages

### ISSUE THREAD

**Issue by VanessaDiBella** [jukrams/workout-planner#25]
## Value proposition
As a user
I want to have a home page as first page
To have a clear page hierarchy 
## Description
![Home](https://github.com/user-attachments/assets/5d688551-c08f-41e4-9d28-86fdc4ba20be)
## Acceptance criteria
- [x] "/" URL goes to the homepage
- [x] "/exercise" URL goes to the exercise page
## Tasks
- [x] Create a new branch called feature/switch-pages
- [x] Create a new index.js file in pages/exercises
- [x] Copy the code from pages/index.js and paste it in pages/exercises/index.js
- [x] Make sure that every import path is still right and adjust if necessary 
- [x] Copy the code from pages/home.js and paste it in pages/index.js
- [x] Make sure that every import path is still right and adjust if necessary 
- [x] Change in pages/index.js the "start" link path to /exercises

**Comment by Roland-Hufnagel** [comment]
This is a nice but very xxxxs Userstory 😀
