### ISSUE TITLE
Workout Progress

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#26]
## Value proposition
As a user
I want to be abled to check off the exercises I have completed
In order to see my progress

## Description
<img src="https://github.com/user-attachments/assets/9bba48dd-823b-4117-84a8-522f13218237" alt="Wireframe" width="200"/>

## Acceptance criteria
- [x] Each workout's exercise has an opportunity to tick a box once you've completed it
- [x] The progress is visualized in a progress bar
- [x] When completing the workout, a success message is displayed
- [x] Add a button to reset the progress so you can complete the workout again

## Tasks
- [x] Create feature branch feature/workout-progress
- [x] In the Workout component, add a check button for each exercise
- [x] In the Workout component add a progress bar that fills in proportion to the checked checkboxes
- [x] When every checkbox is checked, add a toast message "Congratulations! Workout completed successfully!"
- [x] Save progress in session storage state "workoutProgress"
- [x] In the WorkoutsList component, add a reset button for each list item
- [x] Clicking the button deletes the progress
- [x] Write a function handleResetProgress. The function should resetthe progress state

**Comment by Roland-Hufnagel** [comment]
LGTM
