### ISSUE TITLE
Search Exercises

### ISSUE THREAD

**Issue by Abvali** [jukrams/workout-planner#29]
## Value proposition
As a user
I want the ability to quickly find specific exercises
In order to find exercises that match my interests or preferences
## Description
![Searchbar](https://github.com/user-attachments/assets/7017e204-3f1e-4922-adc4-e88895e5fc6c)

## Acceptance criteria
- [x] The exercise list page includes a Search Input field to search specific exercises.
- [x] The user can search for specific exercises, by typing them into the search input field.
- [x] The search bar includes search button or icon that users can click on to initiate the search.
- [x] The search bar provides real-time suggestions based on the entered text.
- [x] When the search does not match anything, a message indicating this is displayed

## Tasks
- [x] Create feature branch feature/searchbar
- [x] Create searchBar component
- [x] add the searchBar Component to the exercise list page
- [x] implement the search bar with an input field in searchBar component
- [x] Create useState const [searchInput, setSearchInput] = useState("")
- [x] implement the filter functionality to render only matching results
- [x] Add the feature to display a message when no search results are found

**Comment by NikRoe** [comment]
Hi there,

this looks like a neat feature for your application and your user story covers all the "happy cases".

However, what would happen if a user searched for an exercise that did not exist? 🤔

**Comment by NikRoe** [comment]
Hi there,

the description looks good!

Please add this point to your Acceptance Criteria:
- [ ] When the search does not match anything, a message indicating this is displayed

After having done so, this US is approved
