### ISSUE TITLE
Workouts List

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#3]
## Value proposition
As a user
I want to browse a list of workouts,
so that I can discover new workout routines to follow.

## Description
<img src="https://github.com/user-attachments/assets/f82ac1f6-669b-4591-b944-210f686ef75f" alt="Wireframe #3" width="400"/>

## Acceptance criteria
- [x] There is a dedicated page for the workouts list.
- [x] The workouts list page is accessible from the homepage via a link.
- [x] The workouts list page includes a link back to the homepage.
- [x] The page is headlined with its purpose.
- [x] Each workout listing includes: Workout name, Exercises with sets and reps, All muscle groups involved in the workout
- [x] The list supports vertical scrolling to accommodate multiple entries.

## Tasks
- [x] Create feature branch feature/workouts-list
- [x] Inspect and adapt the example data in the [assets folder](https://github.com/neuefische/hh-web-24-5/blob/main/capstone/workout-planner/assets/workouts.json)
- [x] -----
- [x]  Create the component WorkoutsList to render a list
- [x] WorkoutsList props: workouts
- [x] Create the component WorkoutPreview
- [x] WorkoutPreview props: name, exercises
- [x] Create the page pages/workouts/index.js that renders the WorkoutsList component
- [x] Adapt the page pages/index.js: rename the function to ExercisesPage and have it render the ExercisesList component
- [x] Create the page pages/exercices/index.js that renders the Exercises component
- [x] Create the component Navigation that renders all navigation links
- [x] Create the component Layout that renders the Navigation component
- [x] Apply the Layout component in pages/_app
