### ISSUE TITLE
Set a database

### ISSUE THREAD

**Issue by VanessaDiBella** [jukrams/workout-planner#31]
## Value proposition
As a user
I want my data to be stored in a database,
so that I have access to it from several devices.
## Acceptance criteria
- [x]  Workout data will be stored and updated, when workouts get created, read, updated or deleted
- [x] Able to access the data from different devices
## Tasks

- [x] Create a new branch feature/database

**Set Database**
- [x] Go to Mongodb and create a new project called Capstone
- [x] Create a collection called Workouts in a new Cluster
- [x] Import the data from the lib/wokrouts.js file
- [x] Create a new .env.local file at the root of the app and import your path with this structure MONGODB_URI=mongodb+srv://<user>:<password>@<cluster-name>/<name-database>?retryWrites=true&w=majority

**Read**

- [x] Connect the Cluster with the app via **npm install mongoose**
- [x] Write a Schema placed in the db/models You can look this up [here](https://github.com/neuefische/hh-web-24-5/blob/main/sessions/backend-read/backend-read.md) 
- [x] Use the following schema for Workout:
{"name": string,
    "exercises": [
      {
        "exerciseId": string,
        "sets": number,
        "reps": number
      },
    ]
  },
- [x] Connect the database with 'dbConnect()'
- [x] Create a 'db/connect.js' file and copy the [content from the Next.js mongoose example](https://github.com/neuefische/hh-web-24-5/blob/main/sessions/backend-read/assets/dbConnect.js)
- [x] Go to 'api/workouts/index.js' , import 'Workout'  and write a request handler which connects to the database with dbConnect(), uses the Model to search a document, and returns the data.
- [x] Make the `handler` function `async` and `await` the connection to the database.
- [x] If the `request.method` is `GET`, use the 'Workout' model to find all products and return them as a response.
- [x] Switch to 'components/WorkoutsList' and adapt the frontend by replacing all instances of 'workout.id' with 'workout._id'
- [x] if everything works, delete lib/workout.js

**Create**

- [x] Switch to pages/api/workouts/index.js and write the code for the request.method POST 
- [x] Use a try..catch block
- [x] Define a POST API route and call the .create method on our Workout model
- [x] Save the product data submitted by the form - accessible in request.body - to a variable called workoutData.
- [x] use Workout.create with the workoutData to create a new document in your collection.
- [x] Wait until the new product was saved.
- [x] Respond with a status 201 and the message { status: "Product created." }.
- [x] If an error occurs: Log the error to the console and Respond with a status 400 and the message { error: error.message }

**Update**

- [x] Switch to 'pages/api/workouts/[id].js' and write the code for the request.method 'PUT': 
-Get the updated workout from the request body: 'const updatedWorkout = request.body'
- _Wait_ for 'Workout.findByIdAndUpdate(id, updatedWorkout)'.
- Respond with a status 200 and the message { status: "Workout successfully updated." }
- [x] Switch to `./components/WorkoutForm/index.js`.
- [x] Lift up all logic regarding the creating of the `WorkoutData` to the ./pages/workout.js file
- [x] Rename the `handleSubmit` function to `handleAddWorkout`
- [x] in the return statement, pass `handleAddWorkout` to the WorkoutForm component as a prop called `onSubmit`.
- [x] Switch back to `./components/WorkoutForm/index.js` an receive the onSubmit prop and use onSubmit instead of handleSubmit in the form
- [x] Switch to components/Wokouts/index.js
- [x] Below this code, create a `handleEditWorkout()` function:
- it starts a "PUT" request with `fetch`

**Delete**

- [x] Switch to pages/api/workouts/[id].js and write the code for the request.method DELETE :
- _Wait_ for `Workout.findByIdAndDelete(id)`.
- Respond with a status `200` and the message `{ status: "Workout successfully deleted." }`.
- [x] Switch to component/workout.js and add `onClick={() => handleDeleteProduct(id)}`  to the delete Button
- [x] Write the `handleDeleteProduct` function:
- _Wait_ for a `fetch()` with two arguments:
  - the url `/api/workouts/${id}` and
  - an options object `{ method: "DELETE" }`
- Save the result in a variable called `response`.
- If the `response` is `ok`,
  - _wait_ for `response.json()` and use `push("/")`.
- If the `response` is not `ok`, log the `response.status` as an error to the console.

**Comment by NikRoe** [comment]
Hi there,

promising start!

The users won't get access to the database. But your data will be stored in one so that user data does not get lost.
Your value proposition could look like this:
As a user,
I want my data to be stored in a database,
so that I have access to it from several devices.

I would leave out the image in the description.

The Acceptance Criteria should focus on describing how the application will behave from the user's perspective once the feature is implemented. In your case, users are not concerned with the technical details like MongoDB, clusters, or project members' access. What matters to them is that when they perform CRUD operations, the changes they make to their workout data will be consistently updated and reflected on any device they use to connect to your application.

Please update your user story according to the suggestions.

Cheers ✌️
