### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#32]
## Value proposition
As a registered user
I want to log into the web app
So that I can access my personalized content and features.

## Description
<img src="https://github.com/user-attachments/assets/0f1d3720-af2a-4897-a742-0f769dabdf7b" alt="Wireframe" width="200"/>

## Acceptance criteria
- [x] I can navigate to the login page, where I see options to sign in with various providers (e.g., Google, GitHub).
- [x] If I sign in using a provider like Google or GitHub, I am redirected to the provider’s login page.
- [x] After successful authentication with the provider, I am redirected back to the web app, and my session is created.
- [x] I can access my personalized user area while logged in.
- [x] My session persists across page reloads and until it expires or I log out.
- [x] I can log out of the web app at any time using a "Sign Out" button provided by NextAuth.js.
- [x] After logging out, I am redirected to the homepage or a specified post-logout page, and my session is destroyed.

## Tasks
- [x] Create a new branch called feature/user-login.
- [x] Install the next-auth library with `npm install next-auth`.
- [x] Create the file` pages/api/auth/[...nextauth].js` to configure NextAuth.js.
- [x] Add the configuration for the desired authentication providers (e.g., Google, GitHub) in this file.
- [x] Create the SignIn component in `components/SignIn.js`.
- [x] This component should render the login options for the various authentication providers.
- [x] The page `pages/index.js` should render the SignIn component and serve as the main sign-in page.
- [x] Import and use the SessionProvider from NextAuth.js to make the session available across the entire app.
- [x] Wrap the Component in _app.js with the SessionProvider.
- [x] Create a withAuth HOC (Higher-Order Component) or use getSession and getServerSideProps to implement protected pages.
- [x] Apply the HOC or functions to pages that require authentication.
- [x] Update the Navigation component to display "Sign In" and "Sign Out" links based on the user's authentication status.
- [x] Use useSession from NextAuth.js to check the login state and display the appropriate links.
- [x] Implement the sign-out functionality, allowing users to log out when clicking "Sign Out."
- [x] Use the signOut function from NextAuth.js for this purpose.

**Comment by NikRoe** [comment]
Hi there,

promising start!

The Acceptance Criteria should focus on describing how the application will behave from the user's perspective once the feature is implemented and not on technical details.

That means you can/should remove these points from the AC:
- The web app is set up to use NextAuth.js for handling authentication.
- NextAuth.js is configured with one or more authentication providers (e.g., Google, GitHub, or Email).
- The necessary environment variables for client IDs, secrets, and callback URLs are correctly configured.
-  After a successful login, my session is managed by NextAuth.js, which stores the session securely using JWT or database sessions.
 - NextAuth.js handles token management and session security, ensuring that my data is protected.
 - All sensitive data is transmitted over HTTPS, and session cookies are secured with proper flags (e.g., httpOnly, secure).

And I have a question regarding one point:
- Certain routes in the web app are protected and require authentication to access. -> what are those routes? Please specify them.

Please update your user story accordingly.

Cheers ✌️
