### ISSUE TITLE
Create Workout

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#4]
## Value proposition
As a user
I want to create and store new workouts,
so that I can have a personalised workout plan that suits my fitness goals.

## Description
<img src="https://github.com/user-attachments/assets/6bf22981-a245-4d37-bdc1-e3553589aa2b" alt="Wireframe #4" width="400"/>

## Acceptance criteria
- [x] A form for adding workouts is displayed at the top of the workouts list page.
- [x] The form is headlined with its purpose.
- [x] The form comprises labeled fields for: Workout name, Exercise name (dynamic form fields), Exercise sets (dynamic form fields), Exercise reps (dynamic form fields)
- [x] The following fields are mandatory: Workout name, Exercise name (at least one exercise must be added), Exercise sets (minimum 1), Exercise reps (minimum 1)
- [x] The exercise is selected from the existing exercises list via a dropdown menu.
- [x] The exercise dropdown must include a default option, "Please select an exercise", and necessitates a selection.
- [x] Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- [x] Upon form submission, the new workout is added to the top of the workouts list.

## Tasks
- [x] Create feature branch feature/create-workout
- [x] -----
- [x] Install `use-local-storage-state`
- [x] In `pages/workouts/index.js` import useLocalStorageState from "use-local-storage-state" and create a local storage state for "workouts"
- [x] Create a WorkoutForm component to render a form
- [x] The WorkoutForm is rendered in the WorkoutsList component
- [x] Form props: onAddWorkout
- [x] In `pages/workouts/index.js`, write a function `handleAddWorkout` which accepts a new workout object as parameter and adds this object to the workouts state
- [x] Please add a unique id to every new activity object,  use [uid](https://www.npmjs.com/package/uid) to do so

**Comment by MerleMak** [comment]
If you set up a database at this point you need to think about your exact data structure in the database. Is there one collection workouts and one collection exercises? I would highly recommend making it two different collections and reference the ids of the exercises in an array within each workout object in the collection. 
If you add the workouts to the database you also need to move the exercises to the database. You need to specify all of that in the userstory including the schema for mongoose. Therefore I recommend to make the database access a single US and use Lcoal Storage to make them persistent for nowö
