### ISSUE TITLE
Update Workout

### ISSUE THREAD

**Issue by EmmaDir** [jukrams/workout-planner#6]
## Value proposition
As a user
I want to update the details of existing workouts,
so that my workout routines remain accurate and aligned with my fitness goals.

## Description
<img src="https://github.com/user-attachments/assets/937f070c-b3d9-417d-a1c5-73247e4c14b5" alt="Wireframe #3" width="400"/>

## Acceptance criteria
- [x] The workouts list page includes an easily accessible edit option for each workout.
- [x] Clicking the edit option opens a new page with a form pre-filled with the workout’s existing details for modification.
- [x] The form allows for edits to all workout details, including: Workout name, Exercise name (dynamic form fields), Exercise sets (dynamic form fields), Exercise reps (dynamic form fields)
- [x] The following fields are mandatory: Workout name, Exercise name (at least one exercise must be included), Exercise sets (minimum 1), Exercise reps (minimum 1)
- [x] The exercise selection must include a dropdown to choose exercises from the existing exercise list.
- [x] The form section includes options for both saving and cancelling the action.
- [x] The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- [x] Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- [x] Upon confirming the save, the user is immediately redirected to the workouts list page, and the changes are saved and reflected.

## Tasks
- [x] Create feature branch feature/update-workout
- [x] -----
- [x] In the WorkoutsList component, add a edit button for each list item
- [x] By clicking the button open the page `pages/workouts/edit.js`
- [x] The page renders the WorkoutForm component
- [x] The WorkoutForm component needs to receive a new prop called isEditMode
- [x] If isEditMode, add a cancel and save button
- [x] When clicking the cancel button, direct back to `pages/workouts/index.js`
- [x] The WorkoutForm component needs to receive a new prop called onUpdateWorkout
- [x] Pass it to the save button as onClick prop
- [x] Pass the workout's id to onUpdateWorkout as argument
- [x] In pages/workouts/index.js, write a function handleUpdateWorkout, which accepts an id as parameter. The function should update the workouts state and keep all objects except the one with the given id. Use the form's values ​​instead. The user should be redirected back to `pages/workouts/index.js`
- [x] Pass handleUpdateWorkout to the List component as onUpdateWorkout prop

**Comment by MerleMak** [comment]
How to you want to "handleUpdateWorkout"? 
Find or Filter? And after? You don't need to write this down, but think about it :)
